// combinedData.js

export const allData = [
  // 📘 Fiction
  ...[
    {
      id: 1,
      title: "연성 1",
      name: "괴",
      key: 0,
      rating: 15,
      sentence:
        "몇자까지 가능한지 테스트 하는 중입니다. 이렇게 길어지면 어떻게 될까요? ",
      password: null,
      hint: null,
      iframe: `<iframe
          width="560"
          height="315"
          src="https://www.youtube.com/embed/sggpznX28_4?si=XMW_yfEpVQPQ7430"
          title="YouTube video player"
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          referrerpolicy="strict-origin-when-cross-origin"
          allowfullscreen
        ></iframe>`,
      hasSymbols: false,
    },
    {
      id: 2,
      title: "아름다운것들",
      name: "구가",
      key: 1,
      rating: 12,
      sentence:
        "두 번째 테스트. 몇자까지 가능한지 테스트 하는 중입니다. 이렇게 길어지면 어떻게 될까요?",
      password: null,
      hint: null,
      iframe: null,
      hasSymbols: false,
    },
    {
      id: 3,
      title: "오네가이 오코시테",
      name: "리시타",
      key: 2,
      rating: 12,
      sentence: null,
      password: null,
      hint: null,
      iframe: null,
      hasSymbols: false,
    },
    {
      id: 4,
      title: "yuma",
      name: "마주랑",
      key: 3,
      rating: 12,
      sentence: "문장4자리입니다",
      password: null,
      hint: null,
      iframe: null,
      hasSymbols: false,
    },
    {
      id: 5,
      title: "ユ're マine",
      name: "멜",
      key: 4,
      rating: 19,
      sentence: null,
      password: "061505",
      hint: "https://ridibooks.com/books/845039101",
      iframe: `<iframe width="560" height="315" src="https://www.youtube.com/embed/qNU-SUKjMz0?si=YI0PPtyZrxWg8Pur" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`,
      hasSymbols: false,
    },
    {
      id: 6,
      title: "코인이 하나 더 생겼으면 또 해야겠지",
      name: "밍이",
      key: 5,
      rating: 12,
      sentence: null,
      password: null,
      hint: null,
      iframe: null,
      hasSymbols: false,
    },
    {
      id: 7,
      title: "누구도 잘못하지 않았다.",
      name: "방토",
      key: 6,
      rating: 12,
      sentence: "나 지금 코마 상태인가?",
      password: null,
      hint: null,
      iframe: null,
      hasSymbols: false,
    },
    {
      id: 8,
      title: "제목8",
      name: "분점",
      key: 7,
      rating: 12,
      sentence: "문장 8자리입니다!!",
      password: null,
      hint: null,
      iframe: null,
      hasSymbols: false,
    },
    {
      id: 9,
      title: "비하인드 더 씬",
      name: "소바",
      key: 8,
      rating: 12,
      sentence: "떠나야 끝나는 이야기도 있는 거예요.",
      password: null,
      hint: null,
      iframe: null,
      hasSymbols: false,
    },
    {
      id: 10,
      title: "제목10",
      name: "쏘와",
      key: 9,
      rating: 12,
      sentence: "十五夜",
      password: null,
      hint: null,
      iframe: null,
      hasSymbols: false,
    },
    {
      id: 11,
      title: "사랑을 알까.",
      name: "아라",
      key: 10,
      rating: 12,
      sentence: "네가 내 걱정을 다 하고. 이제 여유도 있나 봐?",
      password: null,
      hint: null,
      iframe: `<iframe width="560" height="315" src="https://www.youtube.com/embed/U9p4zHlb5fM?si=CiOKjrSld2H6C47C" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`,
      hasSymbols: true,
    },
    {
      id: 12,
      title: "제목12",
      name: "참외",
      key: 12,
      rating: 12,
      sentence: "やだ！",
      password: null,
      hint: null,
      iframe: null,
      hasSymbols: false,
    },
    {
      id: 13,
      title: "귀 빠진 날",
      name: "코도모",
      key: 13,
      rating: 15,
      sentence: "chu- chu-",
      password: null,
      hint: null,
      iframe: `<iframe width="560" height="315" src="https://www.youtube.com/embed/PGADim6UzHE?si=1t_5Zyng69n0RUzE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`,
      hasSymbols: false,
    },
    {
      id: 14,
      title: "제목14",
      name: "코이",
      key: 14,
      rating: 12,
      sentence: "14th content",
      password: null,
      hint: null,
      iframe: null,
      hasSymbols: false,
    },
    {
      id: 15,
      title: "제목15",
      name: "희지",
      key: 15,
      rating: 12,
      sentence: "wolf type",
      password: null,
      hint: null,
      iframe: null,
      hasSymbols: false,
    },
    {
      id: 16,
      title:
        "게임 오타쿠였던 내가 고양이의 은혜를 입어 현관 밖 세상에 출석하게 된 건에 대하여",
      name: "Nama",
      key: 16,
      rating: 12,
      sentence: "그러면 언젠가 만렙이 될 수 있지 않을까요? 이 세상에서도.",
      password: null,
      hint: null,
      iframe: null,
      hasSymbols: true,
    },
    {
      id: 17,
      title: "제목17",
      name: "익명 A",
      key: 17,
      rating: 12,
      sentence: "타키타키타키",
      password: null,
      hint: null,
      iframe: null,
      hasSymbols: false,
    },
    {
      id: 18,
      title: "제목18",
      name: "익명 B",
      key: 18,
      rating: 12,
      sentence: "유마유마유마유마유마",
      password: null,
      hint: null,
      iframe: null,
      hasSymbols: false,
    },
  ].map((item) => ({ ...item, type: "Fiction" })),

  // 🎨 Artwork
  ...[
    {
      guest: false,
      title: "TAKI",
      name: "감",
      key: 101,
      id: 101,
      thumb: "/img/img1.jpeg",
      src: ["/img/img1.jpeg"],
      rating: 15,
      password: "321162",
      sentence:
        "세 번째 테스트. 몇자까지 가능한지 테스트 하는 중입니다. 이렇게 길어지면 어떻게 될까요?",
      hint: "https://ridibooks.com/books/2498003915",
      iframe: null,
    },
    {
      guest: false,
      title: "yuma",
      name: "개미의 생각",
      key: 102,
      id: 102,
      thumb: "/img/img2.jpeg",
      src: ["/img/img2.jpeg"],
      rating: 15,
      password: null,
      sentence: "タキとゆうま",
      hint: null,
      iframe: null,
    },
    {
      guest: false,
      title: "신령님의 신부!!가 되어버렸습니다!",
      name: "라미",
      key: 103,
      id: 103,
      thumb: "/img/rami-thumb.png",
      src: [
        "/img/rami-1.png",
        "/img/rami-2.png",
        "/img/rami-3.png",
        "/img/rami-4.png",
        "/img/rami-5.png",
        "/img/rami-6.png",
        "/img/rami-7.png",
        "/img/rami-8.png",
        "/img/rami-9.png",
        "/img/rami-10.png",
        "/img/rami-11.png",
        "/img/rami-12.png",
        "/img/rami-13.png",
        "/img/rami-14.png",
        "/img/rami-15.png",
        "/img/rami-16.png",
        "/img/rami-17.png",
        "/img/rami-18.png",
        "/img/rami-19.png",
        "/img/rami-20.png",
        "/img/rami-21.png",
        "/img/rami-22.png",
        "/img/rami-23.png",
        "/img/rami-24.png",
        "/img/rami-25.png",
        "/img/rami-26.png",
        "/img/rami-27.png",
        "/img/rami-28.png",
        "/img/rami-29.png",
        "/img/rami-30.png",
        "/img/rami-31.png",
        "/img/rami-32.png",
        "/img/rami-33.png",
        "/img/rami-34.png",
        "/img/rami-35.png",
        "/img/rami-36.png",
      ],
      rating: 15,
      password: null,
      sentence: "그... 정기라는 거 지금... 하는거죠?",
      hint: null,
      iframe: `<iframe width="560" height="315" src="https://www.youtube.com/embed/kXhlh3oKo9k?si=_bhF7KCJxN4TDKfi" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`,
    },
    {
      guest: false,
      title: "4컷만화",
      name: "오비",
      key: 104,
      id: 104,
      thumb: "/img/img4.jpeg",
      src: ["/img/img4.jpeg"],
      rating: 15,
      password: null,
      sentence:
        "어떤 대사까지 가능한지 테스트 하는 중입니다. 이것보다 더 길어지면 말풍선이 감당할 수 있을지 모르겠네요.",
      hint: null,
      iframe: null,
    },
    {
      guest: false,
      title: "쿠헤헤헤헬",
      name: "외네",
      key: 105,
      id: 105,
      thumb: "/img/img5.jpeg",
      src: ["/img/img5.jpeg"],
      rating: 15,
      password: null,
      sentence: "이모티콘도 🍟 🌯 ☕️",
      hint: null,
      iframe: null,
    },
    {
      guest: false,
      title: "雪あかり",
      name: "일호",
      key: 106,
      id: 106,
      thumb: "/img/img6.jpeg",
      src: ["/img/img6.jpeg"],
      rating: 15,
      password: null,
      sentence: "어떤 작품들이 들어올까. 기대돼! 꺅",
      hint: null,
      iframe: null,
    },
    {
      guest: false,
      title: "number 666",
      name: "픽",
      key: 107,
      id: 107,
      thumb: "/img/img7.jpeg",
      src: ["/img/img7.jpeg"],
      rating: 15,
      password: null,
      sentence: "Big suki",
      hint: null,
      iframe: null,
    },
    {
      guest: false,
      title: "만화",
      name: "하파",
      key: 108,
      id: 108,
      thumb: "/img/img8.jpeg",
      src: ["/img/img8.jpeg"],
      rating: 15,
      password: null,
      sentence: "Go in Blind",
      hint: null,
      iframe: null,
    },
    {
      guest: false,
      title: "만화",
      name: "Dana",
      key: 109,
      id: 109,
      thumb: "/img/img8.jpeg",
      src: ["/img/img8.jpeg"],
      rating: 12,
      password: null,
      sentence: "아홉작품이나 들어온다구요><",
      hint: null,
      iframe: null,
    },
    {
      guest: true,
      title: "여름밤의 단맛",
      name: "깨돌이",
      key: 110,
      id: 110,
      thumb: "/img/kkae-thumb.jpg",
      src: ["/img/kkae-1.jpg", "/img/kkae-2.jpg", "/img/kkae-3.jpg"],
      rating: 19,
      password: "820715",
      sentence: "저도 많이 좋아해요.",
      hint: "https://ridibooks.com/books/4798000001",
      iframe: null,
    },
    {
      guest: true,
      title: "제목",
      name: "야키",
      key: 111,
      id: 111,
      thumb: "/img/kkae-thumb.jpg",
      src: ["/img/img1.jpeg"],
      rating: 12,
      password: null,
      sentence:
        "세 번째 테스트. 몇자까지 가능한지 테스트 하는 중입니다. 이렇게 길어지면 어떻게 될까요?",
      hint: "https://ridibooks.com/books/2498003915",
      iframe: null,
    },
    {
      guest: true,
      title: "제목",
      name: "Ko",
      key: 112,
      id: 112,
      thumb: "/img/kkae-thumb.jpg",
      src: ["/img/img1.jpeg"],
      rating: 15,
      password: null,
      sentence: null,
      hint: "https://ridibooks.com/books/2498003915",
      iframe: null,
    },
  ].map((item) => ({ ...item, type: "Artwork" })),

  // 💬 After
  ...[
    { id: 201, name: "감", file: `/data/after1.txt` },
    { id: 202, name: "개미의 생각", file: `/data/after2.txt` },
    { id: 203, name: "괴", file: `/data/after3.txt` },
    {
      id: 204,
      name: "구가",
      file: `/data/after4.txt`,
    },
    { id: 205, name: "깨돌이", file: `/data/after5.txt` },
    { id: 206, name: "라미", file: `/data/after6.txt` },
    { id: 207, name: "리시타", file: `/data/after7.txt` },
    { id: 208, name: "마주랑", file: `/data/after8.txt` },
    {
      id: 209,
      name: "멜",
      file: `/data/after9.txt`,
    },
    { id: 210, name: "밍이", file: `/data/after10.txt` },
    { id: 211, name: "방토", file: `/data/after11.txt` },
    { id: 212, name: "분점", file: `/data/after12.txt` },
    { id: 213, name: "소바", file: `/data/after13.txt` },
    { id: 214, name: "쏘와", file: `/data/after14.txt` },
    { id: 215, name: "아라", file: `/data/after15.txt` },
    { id: 216, name: "오비", file: `/data/after16.txt` },
    { id: 217, name: "외네", file: `/data/after17.txt` },
    { id: 218, name: "일호", file: `/data/after18.txt` },
    { id: 219, name: "참외", file: `/data/after19.txt` },
    { id: 220, name: "코도모", file: `/data/after20.txt` },
    { id: 221, name: "코이", file: `/data/after21.txt` },
    { id: 222, name: "픽", file: `/data/after22.txt` },
    { id: 223, name: "하파", file: `/data/after23.txt` },
    { id: 224, name: "희지", file: `/data/after24.txt` },
    { id: 225, name: "Dana", file: `/data/after25.txt` },
    { id: 226, name: "Ko", file: `/data/after26.txt` },
    { id: 227, name: "Nama", file: `/data/after27.txt` },
    { id: 238, name: "YAKI", file: `/data/after28.txt` },
    { id: 229, name: "익명A", file: `/data/after29.txt` },
    { id: 230, name: "익명B", file: `/data/after30.txt` },
  ].map((item) => ({
    ...item,
    title: null,
    rating: 0,
    password: null,
    sentence: item.content,
    hint: null,
    type: "After",
  })),
];
